version: '3.8'

services:
  hardware-monitor:
    build: .
    container_name: hardware_monitor_api
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always